apiVersion: batch/v1
kind: Job
metadata:
  name: mlflow-webhook-creator
  namespace: webhooks
spec:
  template:
    spec:
      containers:
      - name: mlflow-webhook-creator-container
        image: prashalruchiranga/news-classification:webhook-creator-arm64
        imagePullPolicy: Always
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow.mlflow.svc.cluster.local:80"
        - name: MLFLOW_WEBHOOK_RECEIVER_URI
          value: "https://mlflow-webhook-receiver-1002679294053.us-central1.run.app/webhook"
        - name: MLFLOW_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: mlflow-webhook-secret
              key: SECRET
      restartPolicy: Never
  backoffLimit: 10
