# PIPELINE DEFINITION
# Name: news-clf-model-trainer
# Description: Pipeline to fine-tune a pre-trained BERT model for news classification
# Inputs:
#    batch_size: int [Default: 32.0]
#    bert_preset: str [Default: 'bert_tiny_en_uncased']
#    dataset_name: str
#    dataset_split_seed: int [Default: 42.0]
#    debug_batch_count: int
#    early_stopping_min_delta: float [Default: 0.001]
#    epochs: int [Default: 20.0]
#    label_column_name: str
#    learning_rate: float [Default: 5e-05]
#    max_no_improve_epochs: int [Default: 5.0]
#    text_column_name: str
#    val_data_fraction: int [Default: 0.2]
components:
  comp-finetune-bert:
    executorLabel: exec-finetune-bert
    inputDefinitions:
      artifacts:
        train_dataset:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        val_dataset:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
      parameters:
        batch_size:
          parameterType: NUMBER_INTEGER
        debug_batch_count:
          parameterType: NUMBER_INTEGER
        epochs:
          parameterType: NUMBER_INTEGER
        label_col:
          parameterType: STRING
        lr:
          parameterType: NUMBER_DOUBLE
        min_delta:
          parameterType: NUMBER_DOUBLE
        patience:
          parameterType: NUMBER_INTEGER
        preset:
          parameterType: STRING
        text_col:
          parameterType: STRING
    outputDefinitions:
      artifacts:
        saved_model:
          artifactType:
            schemaTitle: system.Model
            schemaVersion: 0.0.1
  comp-load-hf-dataset:
    executorLabel: exec-load-hf-dataset
    inputDefinitions:
      parameters:
        name:
          parameterType: STRING
        seed:
          parameterType: NUMBER_INTEGER
        val_fraction:
          parameterType: NUMBER_INTEGER
    outputDefinitions:
      artifacts:
        preview:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        test_dataset:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        train_dataset:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        val_dataset:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
deploymentSpec:
  executors:
    exec-finetune-bert:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - finetune_bert
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.13.0'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"'  &&\
          \  python3 -m pip install --quiet --no-warn-script-location 'datasets>=4.0.0'\
          \ 'tensorflow==2.18.0' 'keras-hub>=0.22.1' && \"$0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef finetune_bert(\n    preset: str,\n    batch_size: int,\n    text_col:\
          \ str,\n    label_col: str,\n    lr: float,\n    epochs: int,\n    min_delta:\
          \ float,\n    patience: int,\n    debug_batch_count: int,\n    train_dataset:\
          \ Input[Dataset],\n    val_dataset: Input[Dataset],\n    saved_model: Output[Model]\n\
          \    ):\n    import os\n    import json\n    from datasets import load_from_disk\n\
          \    from keras_hub.models import BertTextClassifier\n    from tensorflow.keras.losses\
          \ import SparseCategoricalCrossentropy\n    from tensorflow.keras.metrics\
          \ import SparseCategoricalAccuracy\n    from tensorflow.keras.optimizers\
          \ import Adam\n    from tensorflow.keras.callbacks import EarlyStopping\n\
          \n    # shift [1,2,3,4] -> [0,1,2,3]\n    def adjust_labels(x, y):\n   \
          \     return x, y - 1\n\n    train_split = load_from_disk(train_dataset.path)\n\
          \    val_split = load_from_disk(val_dataset.path)\n    tf_train_dataset\
          \ = train_split.to_tf_dataset(\n        columns=[text_col],\n        label_cols=[label_col],\n\
          \        batch_size=batch_size,\n        shuffle=True\n    )\n    tf_val_dataset\
          \ = val_split.to_tf_dataset(\n        columns=[text_col],\n        label_cols=[label_col],\n\
          \        batch_size=batch_size,\n        shuffle=True\n    )\n    tf_train_dataset\
          \ = tf_train_dataset.map(adjust_labels)\n    tf_val_dataset = tf_val_dataset.map(adjust_labels)\n\
          \n    if debug_batch_count is not None:\n        tf_train_dataset = tf_train_dataset.take(debug_batch_count)\n\
          \        tf_val_dataset = tf_val_dataset.take(debug_batch_count)\n\n   \
          \ number_of_classes = len(set(train_split[label_col]))\n    classifier =\
          \ BertTextClassifier.from_preset(\n        preset=preset,\n        num_classes=number_of_classes,\n\
          \    )\n    classifier.compile(\n        loss=SparseCategoricalCrossentropy(name=\"\
          sparse_categorical_loss\", from_logits=True),\n        metrics = [SparseCategoricalAccuracy(name=\"\
          sparse_categorical_accuracy\")],\n        optimizer=Adam(lr)\n    )\n  \
          \  assert classifier.backbone.trainable == True\n\n    early_stopping =\
          \ EarlyStopping(\n        min_delta=min_delta,\n        patience=patience,\n\
          \        verbose=True,\n        restore_best_weights=True,\n    )\n    history\
          \ = classifier.fit(\n        x=tf_train_dataset,\n        epochs=epochs,\n\
          \        validation_data=tf_val_dataset,\n        callbacks=[early_stopping]\n\
          \    )\n\n    # Save fine-tuned model\n    os.makedirs(saved_model.path,\
          \ exist_ok=True)\n    model_filepath = os.path.join(saved_model.path, \"\
          news_clf_model.keras\")\n    classifier.save(model_filepath)\n\n"
        image: python:3.11-slim
    exec-load-hf-dataset:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - load_hf_dataset
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.13.0'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"'  &&\
          \  python3 -m pip install --quiet --no-warn-script-location 'datasets>=4.0.0'\
          \ && \"$0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef load_hf_dataset(\n    name: str,\n    # Fraction of the training\
          \ dataset to use as the validation split. The validation set is taken from\
          \ the training set, not from the entire dataset\n    val_fraction: int,\n\
          \    seed: int,\n    train_dataset: Output[Dataset],\n    val_dataset: Output[Dataset],\n\
          \    test_dataset: Output[Dataset],\n    preview: Output[Dataset]\n    ):\n\
          \    \"Load a dataset from the Hugging Face Hub and save it as a DatasetDict\
          \ artifact\"\n    from datasets import load_dataset\n    dataset = load_dataset(name)\n\
          \n    # Split train dataset into train split and val split\n    split_dataset\
          \ = dataset[\"train\"].train_test_split(test_size=val_fraction, shuffle=True,\
          \ seed=seed)\n    train_split = split_dataset[\"train\"]\n    val_split\
          \ = split_dataset[\"test\"]\n    # Just take test dataset as test split\n\
          \    test_split = dataset[\"test\"]\n\n    train_split.save_to_disk(train_dataset.path)\n\
          \    val_split.save_to_disk(val_dataset.path)\n    test_split.save_to_disk(test_dataset.path)\n\
          \n    # For preview only\n    df = train_split.to_pandas().head(20)\n  \
          \  df.to_csv(preview.path, index=False)\n\n"
        image: python:3.11-slim
pipelineInfo:
  description: Pipeline to fine-tune a pre-trained BERT model for news classification
  name: news-clf-model-trainer
root:
  dag:
    tasks:
      finetune-bert:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-finetune-bert
        dependentTasks:
        - load-hf-dataset
        inputs:
          artifacts:
            train_dataset:
              taskOutputArtifact:
                outputArtifactKey: train_dataset
                producerTask: load-hf-dataset
            val_dataset:
              taskOutputArtifact:
                outputArtifactKey: val_dataset
                producerTask: load-hf-dataset
          parameters:
            batch_size:
              componentInputParameter: batch_size
            debug_batch_count:
              componentInputParameter: debug_batch_count
            epochs:
              componentInputParameter: epochs
            label_col:
              componentInputParameter: label_column_name
            lr:
              componentInputParameter: learning_rate
            min_delta:
              componentInputParameter: early_stopping_min_delta
            patience:
              componentInputParameter: max_no_improve_epochs
            preset:
              componentInputParameter: bert_preset
            text_col:
              componentInputParameter: text_column_name
        taskInfo:
          name: finetune-bert
      load-hf-dataset:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-load-hf-dataset
        inputs:
          parameters:
            name:
              componentInputParameter: dataset_name
            seed:
              componentInputParameter: dataset_split_seed
            val_fraction:
              componentInputParameter: val_data_fraction
        taskInfo:
          name: load-hf-dataset
  inputDefinitions:
    parameters:
      batch_size:
        defaultValue: 32.0
        isOptional: true
        parameterType: NUMBER_INTEGER
      bert_preset:
        defaultValue: bert_tiny_en_uncased
        isOptional: true
        parameterType: STRING
      dataset_name:
        parameterType: STRING
      dataset_split_seed:
        defaultValue: 42.0
        isOptional: true
        parameterType: NUMBER_INTEGER
      debug_batch_count:
        isOptional: true
        parameterType: NUMBER_INTEGER
      early_stopping_min_delta:
        defaultValue: 0.001
        isOptional: true
        parameterType: NUMBER_DOUBLE
      epochs:
        defaultValue: 20.0
        isOptional: true
        parameterType: NUMBER_INTEGER
      label_column_name:
        parameterType: STRING
      learning_rate:
        defaultValue: 5.0e-05
        isOptional: true
        parameterType: NUMBER_DOUBLE
      max_no_improve_epochs:
        defaultValue: 5.0
        isOptional: true
        parameterType: NUMBER_INTEGER
      text_column_name:
        parameterType: STRING
      val_data_fraction:
        defaultValue: 0.2
        isOptional: true
        parameterType: NUMBER_INTEGER
schemaVersion: 2.1.0
sdkVersion: kfp-2.13.0
