# MLflow related parameters
mlflow_endpoint: "http://localhost:5000"
registered_model: "TinyBertTextClassifier"
alias_to_deploy: "challenger"

# Google Cloud Project related parameters
project_id: "news-classification-472117"
location: "us-central1"
container_image_uri: "us-central1-docker.pkg.dev/news-classification-472117/news-classification/serving-image:v1.0"
endpoint_name: "news-classification-dedicated-endpoint"
machine_type: "e2-standard-2"
